FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install git bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-arm64

ENV VERSION=6.8.0-1010.11
ENV UBUNTU=noble
WORKDIR /code
RUN git clone --branch Ubuntu-raspi-${VERSION} --depth=1 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-raspi/+git/${UBUNTU}

WORKDIR /code/${UBUNTU}
COPY patch/nexmon.6.8.patch /code/

RUN git apply /code/nexmon.6.8.patch
ENV KERNEL=kernel8
# make config
RUN make mrproper
COPY configs/config-${VERSION}-raspi .config
# prepare
RUN make -j `nproc` ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_prepare

# Copy modvers and module.lds
COPY symvers/Module-${VERSION}-raspi.symvers /code/${UBUNTU}/Module.symvers

# Build the nexmon module
RUN make -j `nproc` ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/net/wireless/broadcom/brcm80211/
