FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install git bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-arm64

WORKDIR /code
RUN git clone --branch Ubuntu-raspi-6.2.0-1018.20 --depth=1 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-raspi/+git/lunar

WORKDIR /code/lunar
COPY nexmon.6.2.patch /code/
RUN git apply /code/nexmon.6.2.patch
ENV KERNEL=kernel8
# make config
RUN make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig 
# prepare
RUN make -j `nproc` ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare

# Copy modvers and module.lds
COPY module.lds /code/lunar/scripts/
COPY Module.symvers /code/lunar/

# Build the nexmon module
RUN make -j `nproc` ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/net/wireless/broadcom/brcm80211/
