FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install git bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-arm64

WORKDIR /code
RUN git clone --branch Ubuntu-raspi-6.5.0-1010.13 --depth=1 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-raspi/+git/mantic

WORKDIR /code/mantic
COPY patch/nexmon.6.5.patch /code/
RUN git apply /code/nexmon.6.5.patch
ENV KERNEL=kernel8
# make config
RUN make mrproper
COPY configs/ubuntu-6.5.0-1010.13-config .config
# prepare
RUN make -j `nproc` ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_prepare

# Copy modvers and module.lds
COPY symvers/Module-6.5.0-1010.13.symvers /code/mantic/Module.symvers

# Build the nexmon module
#RUN make -j `nproc` ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/net/wireless/broadcom/brcm80211/
